### ISSUE TITLE
Errors with `fido2 >= 1.0`

### ISSUE THREAD

**Issue by michaelbeaumont** [wuxxin/solo1#1]
I'm running into [this `key set-pin` error](https://github.com/solokeys/solo1-cli/discussions/156), for example. Can this PKGBUILD require `fido2 ~= 0.9` [like in this PR to `solo1-cli`](https://github.com/solokeys/solo1-cli/pull/159/files)?

**Comment by wuxxin** [comment]
to my knowledge, arch packages can not do this. We have to wait until somebody writes a patch for the new api.

As a workaround you can install current solo1 as pipx package:

```
pipx install solo1
```

pipx is installable as python-pipx package.

**Comment by michaelbeaumont** [comment]
Thanks. Using the [above PR pinning `fido2`](https://github.com/solokeys/solo1-cli/pull/159), I got things working with:

```
pipx install git+https://github.com/AlexNigl/solo1-cli@bf43729ccae8bfad2d8d1a269a862c4f80396d19
```
